
---
# config file
name: "wanderer"
domain: "calithos.in/wanderer"
author: "benevolent0377"
github: "https://github.com/benevolent0377/Wanderer"
publicKey: "AAAAC3NzaC1lZDI1NTE5AAAAIOWdfxsz+mL4zmSbDdd7ay50dM3reX2W1ERpBzRh9ttu"
botMailAddr: "wanderer@calithos.in"
knownHostList:
        [
            {name: "yande.re", url: "https://yande.re/post", 404: "Nobody here but us chickens!", imgDelim: '(?<=\"directlink largeimg\" href=).*?(?<=span)', videoDelim: "", loginReq: -1, usr: "", pwd: ""},
            {name: "unknown", url: "", 404: "404", imgDelim: '(href=")+["]$', videoDelim: "", loginReq: -1, usr: "", pwd: ""}
        ]
cmdList: 
        [
            {name: "-h", takesParams: 1, secondaryName: "--help", helpMsg: "Type a command after -h or --help for more information on that specifc command.[EX: --help --host]"},
            {name: "-s", takesParams: 0, secondaryName: "--stor", helpMsg: "Defines the save folder of content downloaded. Default save path is the program's folder /downloads.[EX: -s Pictures/]"},
            {name: "-p", takesParams: 0, secondaryName: "--port", helpMsg: "Specifies a port to establish a connection on.[EX: -p 22]"},
            {name: "-H", takesParams: 0, secondaryName: "--host", helpMsg: "Specifies the site(s) to connect to. Lists are applicable by separating site names with commas AND NO SPACES.[Ex: -H cars.com,trucks.net,pools.me] [EX: -H https://cars.com]"},
            {name: "-t", takesParams: 0, secondaryName: "--timeout", helpMsg: "Set the timeout of the connection. Default is 45 seconds.[EX: -t 60]"},
            {name: "-v", takesParams: 0, secondaryName: "--verbosity", helpMsg: "Determine the amount of text the program outputs. 1 is the lowest and 5 is the highest.[EX: -v 5]"},
            {name: "-A", takesParams: 0, secondaryName: "--attributes", helpMsg: "Define the pages you want to wander. This function utilizes POST. This command can take a single argument or a list of arguments. Lists are applicable by separating pages with commas AND NO SPACES.[Ex: -A cars,trucks,pools] [EX: -A cars]"},
            {name: "-pR", takesParams: -1, secondaryName: "--preserve", helpMsg: "Boolean command. Takes no arguments. Preserves cached program data.[EX: -pR] [EX: --preserve]"}
        ]
