CWD: /home/neon/PycharmProjects/Wanderer/.venv/source
Home-Directory: /home/neon/
OS: linux-6.9.1-zen1-2-zen-x86_64-with-glibc2.39
Program-SerialNo: 1785HX7N2F6ISA2NX1B62WVX
SendLogs: 'True'
Version: 1.0.0 Alpha
